### ISSUE TITLE
(Build-Error): [Dagger-Hilt] cannot access DefaultActivityViewModelFactory

### ISSUE THREAD

**Issue by Marfin12** [dicodingacademy/a165-android-expert-project#4]
It has an error when I click run app on `304-dagger-hilt` branch as drawn picture below. 
<img width="1440" alt="Screen Shot 2021-05-11 at 06 42 34" src="https://user-images.githubusercontent.com/33171451/117737470-2c7eb400-b224-11eb-9d78-ba4fabcb1a95.png">
Please fix it by removing the viewModel dependency: `implementation "androidx.hilt:hilt-lifecycle-viewmodel:$hilt_jetpack_version"`. Thank you very much.

**Comment by arifaizin** [comment]
Saya tidak menemukan error ini ketika mencobanya. Namun dependency tersebut telah kami hapus, karena pada Hilt versi stable sudah tidak membutuhkannya. Terima kasih atas feedback-nya.
